config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :sessions
  root "home#index"

  get '/auth/:provider/callback', to: 'sessions#create'
  get '/auth/failure', to: 'sessions#failure'

  match '/logout', to: "sessions#destroy", via: :all
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include ApplicationHelper
  def require_logged_in
    unless current_user
      redirect_to "/auth/sso"
    end
  end

  

  def login user
    session[:user_id] = user.uid
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :require_logged_in
  def index
    respond_to do |format|
      format.html {render :index}
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  layout "application"
  
  def create
    binding.pry
    @user = User.where(email: auth.info.email, uid: auth.uid).first
    unless @user
      @user = User.new(email: auth.info.email, uid: auth.uid)
    end
    @user.save
    login @user
    redirect_to root_path
  end
  
  def destroy
    session[:user_id] = nil
    redirect_to "#{ENV["PROVIDER_URL"]}/users/logout"
  end

  def failure
  end

  private
  def auth
    request.env['omniauth.auth']
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_user
    @user = User.find_by(uid: session[:user_id]) if session[:user_id]
  end
end

app/views/home/index.html.erb
Hello User 
<p><%= current_user.uid %></p>
<p><%= link_to "Logout", logout_path, method: :delete  %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SsoClient</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>